package com.ishapirov.telegrambot.buttonactions;

public enum ButtonAction {
    GO_TO_MAIN_MENU,
    GO_TO_CATALOG_MENU,
    GO_TO_MANAGER_INFO,
    GO_TO_BASKET,
    GO_TO_CURRENCY_SELECT,
    GO_TO_ORDERS,
    GO_TO_VIEW_REMOVE,
    GO_TO_BOOK_CATALOG,
    PAY,
    BACK_A_BOOK_IN_CART,
    FORWARD_A_BOOK_IN_CART,
    REMOVE_BOOK_FROM_CART,
    BACK_A_BOOK_IN_CATALOG,
    FORWARD_A_BOOK_IN_CATALOG,
    INCREASE_QUANTITY,
    DECREASE_QUANTITY,
    ADD_BOOK_TO_CART,
    GO_TO_KIDS_CATEGORIES,
    GO_TO_PARENTING_CATEGORIES,
    SELECT_USD,
    SELECT_RUB,
    SELECT_UZS
}
